### ISSUE TITLE
global-metadata.dat filesize is zero.

### ISSUE THREAD

**Issue by mrcas** [djkaty/Il2CppInspectorPlugins#3]
Here is the link of game

https://play.google.com/store/apps/details?id=com.fungames.sniper3d&hl=en&gl=US

I am trying to find meta data file on memory but i cannot find it. Can you please spend a little time to make a plugin for it?

I am sorry for disturbing you.

**Comment by djkaty** [comment]
You are referred to the text in README.md and the New issue screen:

>ONLY use the issue tracker to report bugs in plugins.
>
>DO NOT use the issue tracker to request plugins, request features for existing plugins, ask for help with plugins or report bugs in Il2CppInspector. These issues will be ignored. The plugin architecture exists to help you create new functionality, but we do not provide official support or take requests.
